Bugfix: Partial Options Nil Pointer Exception
First, add coverage for passing in keyword options from a Partial's call
site. In support of that coverage, introduce the
`test/fixtures/_columns.html.erb` partial.

Next, add a test to exercise that partial _without_ call site option
overrides. Without the implementation change, that test raises an
exception like:

```
Error:
RendererTest#test_render_without_options_from_call_site:
ActionView::Template::Error: undefined method `merge' for nil:NilClass

      @view_context.tag.public_send(meth, @content + arguments.first.to_s, **options.merge(keywords), &block)
                                                                                    ^^^^^^
    test/renderer_test.rb:38:in `block in <class:RendererTest>'
```

The issue is related to the absence of the `@options` instance variable.
The cause stems from the `#process_options` post-fix conditional
(`unless new_options.empty?`) serving as a guard clause preventing the
`@options` variable's declaration.

To resolve the issue, move the `@options ||= Options.new(@view_context)`
declaration out of `process_options` and into the `Content` constructor
to guarantee that the value is _always_ present.